[package]
name = "fshash"
version = "0.1.0"
authors = ["Muhammad Anjum Kaiser <anjumbutt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
directories-next = "2.0.0"
sha2 = "0.9.1"
sqlite3 = "0.24.0"
